version: '3.8'

services:
  boutique-app:
    build: .
    container_name: boutique-app
    ports:
      - "8081:8085"
    depends_on:
      boutique-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://boutique-db:3306/boutique_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # This will be read from the .env file
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  boutique-db:
    image: mysql:8.0
    container_name: boutique-db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} # This will be read from the .env file
      - MYSQL_DATABASE=boutique_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
