-- =====================================================================
-- V1 — Baseline du schéma (dialecte H2)
-- Généré à partir du DDL produit par Hibernate (schema-generation) pour
-- correspondre EXACTEMENT au schéma que `ddl-auto=update` créait jusqu'ici.
-- Sur une base client déjà créée par ddl-auto, Flyway pose simplement la
-- baseline (baseline-on-migrate) sans rejouer ce script.
-- =====================================================================

create table audit_logs (id bigint generated by default as identity, timestamp timestamp(6) not null, action varchar(255) not null, adresse_ip varchar(255), detail TEXT, entite varchar(255), entite_id varchar(255), type varchar(255) not null, utilisateur varchar(255) not null, primary key (id));
create table caisses (active boolean not null, id bigint generated by default as identity, nom varchar(255) not null unique, primary key (id));
create table clients (date_inscription date not null, solde_credit numeric(38,2) not null, id bigint generated by default as identity, adresse varchar(255), nom varchar(255) not null unique, telephone varchar(255) unique, primary key (id));
create table facture (montant_total numeric(10,2), date_facture timestamp(6) not null, id bigint generated by default as identity, nom_fournisseur varchar(255), numero_facture varchar(255) not null, primary key (id));
create table ligne_ventes (montant_total numeric(38,2) not null, prix_unitaire numeric(38,2) not null, quantite numeric(10,2) not null, id bigint generated by default as identity, produit_id bigint not null, vente_id bigint not null, primary key (id));
create table ligne_facture (montant_total_ligne numeric(10,2), prix_unitaire numeric(10,2) not null, quantite numeric(10,2) not null, facture_id bigint not null, id bigint generated by default as identity, produit_id bigint not null, primary key (id));
create table mouvements_stock (quantite numeric(10,2) not null, date_mouvement timestamp(6) not null, facture_id bigint, id bigint generated by default as identity, produit_id bigint not null, utilisateur_id bigint, description varchar(255), type_mouvement varchar(255) not null check (type_mouvement in ('ENTREE','SORTIE_VENTE','SORTIE_PERTE','PERIME','CASSE_DEFECTUEUX','AVOIR')), primary key (id));
create table panier_temporaire (created_at timestamp(6) not null, id bigint generated by default as identity, tab_id bigint, updated_at timestamp(6) not null, utilisateur_id bigint not null, cart_data TEXT, primary key (id));
create table parametre (cle varchar(255) not null, valeur varchar(255), primary key (cle));
create table personnel (date_embauche date, id bigint generated by default as identity, contact varchar(255), nom varchar(255) not null, poste varchar(255), prenom varchar(255) not null, primary key (id));
create table produits (date_peremption date, prix_achat numeric(38,2), prix_promotionnel numeric(38,2), prix_vente_unitaire numeric(38,2) not null, promotion_active boolean not null, quantite_en_stock numeric(10,2) not null, id bigint generated by default as identity, categorie varchar(100), code_barres varchar(100) unique, numero_facture varchar(100), image_url varchar(255), nom varchar(255) not null, nom_fournisseur varchar(255), unite_de_vente varchar(255), primary key (id));
create table session_caisse (ecart numeric(38,2), montant_final numeric(38,2), montant_initial numeric(38,2) not null, ventes_calculees numeric(38,2), caisse_id bigint, date_fermeture timestamp(6), date_ouverture timestamp(6) not null, ferme_par_utilisateur_id bigint, id bigint generated by default as identity, utilisateur_id bigint not null, primary key (id));
create table utilisateurs (id bigint generated by default as identity, code varchar(255) unique, password varchar(255) not null, roles varchar(255) not null, username varchar(255) not null unique, primary key (id));
create table ventes (montant_paye numeric(38,2), reliquat numeric(38,2), remise numeric(38,2), total numeric(38,2) not null, total_brut numeric(38,2) not null, total_final numeric(38,2) not null, total_net numeric(38,2) not null, client_id bigint, date_vente timestamp(6) not null, id bigint generated by default as identity, session_caisse_id bigint, utilisateur_id bigint, motif_annulation varchar(255), moyen_paiement varchar(255) not null check (moyen_paiement in ('ESPECES','CARTE','MOBILE','CREDIT','CASH')), status varchar(255) not null check (status in ('COMPLETED','CANCELLED')), type_vente varchar(255) not null, primary key (id));

alter table if exists ligne_ventes add constraint FKa4bvxrbpu0aiwsvjgm1mcb3nc foreign key (produit_id) references produits;
alter table if exists ligne_ventes add constraint FKbp3hf3ohuu47g2h3hg7wd68i0 foreign key (vente_id) references ventes;
alter table if exists ligne_facture add constraint FKsqu9tafl4p72j8lym8xl42kg1 foreign key (facture_id) references facture;
alter table if exists ligne_facture add constraint FK6o7nbh7wbc1gww9p3rtulu78q foreign key (produit_id) references produits;
alter table if exists mouvements_stock add constraint FKp98gktu348idryx69556xxjfe foreign key (facture_id) references facture;
alter table if exists mouvements_stock add constraint FK3fbx5f8mbhg0npji5dh5v0f4l foreign key (produit_id) references produits;
alter table if exists mouvements_stock add constraint FKltb0r3dqyhjg2ts7uv964ggod foreign key (utilisateur_id) references utilisateurs;
alter table if exists panier_temporaire add constraint FKkkiyo7o2jsa6ye9po8j1tiwmf foreign key (utilisateur_id) references utilisateurs;
alter table if exists session_caisse add constraint FK9hxve0e66pf0vslrlngsfmaug foreign key (caisse_id) references caisses;
alter table if exists session_caisse add constraint FKpa4pp2dq54mji3u19t18raya3 foreign key (ferme_par_utilisateur_id) references utilisateurs;
alter table if exists session_caisse add constraint FKphi2sb31rb5y447kbijd2nkws foreign key (utilisateur_id) references utilisateurs;
alter table if exists ventes add constraint FKbvx23i6p7wmclguf5x4wbls6e foreign key (client_id) references clients;
alter table if exists ventes add constraint FKfnjivbkmurqkoc1gkr3h44o6n foreign key (session_caisse_id) references session_caisse;
alter table if exists ventes add constraint FKk13gvcv3lkesw73akths1xm9 foreign key (utilisateur_id) references utilisateurs;
